spring.application.name=blogapp

spring.data.mongodb.uri=mongodb+srv://raghu:Raghu12345@cluster0.myrdb.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=blogdb

spring.data.mongodb.auto-index-creation=true

jwt.secret=MySuperSecretKey1234567890!@#$%^&*()ABCDEFGHIJKLMNOP
jwt.expiration=86400000