spring.application.name=blogapp

spring.data.mongodb.uri=mongodb+srv://raghu:Raghu12345@cluster0.myrdb.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=blogdb

spring.data.mongodb.auto-index-creation=true

jwt.secret=VGhpc0lzQVNlY3VyZVNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9u
jwt.expiration=86400000